### ISSUE TITLE
Don't panic

### ISSUE THREAD

**Issue by bitdust** [bitdust/WamaCry#1]
# 不要惊慌
首先，恭喜你终于找到了这里 
被人搞了？还是你自己忘记了怎么“解毒”的方法？  
这并不是真正的病毒，也不可能对你的电脑造成真正的损害。  
如果你真的受到了WamaCry的困扰，请检查文件的默认“打开方式”是否设置正常。
或者将本项目链接发送给你认识的专业人士，解决此问题。

**Comment by simon760512** [comment]
How to change the URL when clicking "Contact Us"? Thanks a lot :)
