### ISSUE TITLE
作为真正的粉丝

### ISSUE THREAD

**Issue by AmazingTaotao** [bitdust/WamaCry#10]
作为真正的粉丝，希望添加新的“the elder”皮肤。

**Comment by bitdust** [comment]
国家决定了，这么艰巨的任务可以交给你了！

**Comment by bitpeach** [comment]
@bitdust 
Dear Commander Bitdust:
       You can solve this! Good Luck! If you can't, I will speak two two lines of verse to encourage you for +1 second.

@AmazingTaotao 
Dear Friend:
        May I ask you that whether you are the friend of @bitdust ?  How do you know he is a magician? 

![img_5212](https://cloud.githubusercontent.com/assets/6924631/26066230/cc80bbb6-39c8-11e7-86b9-55ed598c699c.JPG)
![img_4571](https://cloud.githubusercontent.com/assets/6924631/26066420/5ae5a290-39c9-11e7-9de3-408a40e0cdbc.JPG)
![img_5204](https://cloud.githubusercontent.com/assets/6924631/26066248/d67eb26c-39c8-11e7-9370-a685b1d49043.JPG)
