### ISSUE TITLE
真的加密文件

### ISSUE THREAD

**Issue by tansinan** [bitdust/WamaCry#12]
如果老师要求检查电脑里的文件是不是真的被加密了怎么办= =
要是能用对称加密算法真的把电脑里的文件加密，然后允许把密钥备份到U盘里之类的，那就太好了！

**Comment by bitdust** [comment]
这只是个恶搞软件，真的操作系统的话害怕出问题

**Comment by KiritoMiao** [comment]
YourRansom，自己编译一下，实现方案和真加密一样
