### ISSUE TITLE
macOS 10.12上不显示界面元素

### ISSUE THREAD

**Issue by feicong** [bitdust/WamaCry#14]
使用qt5.8执行`qmake && make`可以正常编译并运行，但运行后不显示界面上的元素效果，包括界面的文本与按钮的文字，可以看到透明的电子计时器信息。

**Comment by bitdust** [comment]
你需要把mod目录放在生成目录里面

**Comment by wafer-li** [comment]
@bitdust mod 放入后显示出了部分元素，但是依旧没有显示文本

**Comment by bitdust** [comment]
文本的问题还真帮不上忙～不过既然你有编译能力，可以用0.2版本的代码自己编译，修改界面

**Comment by wafer-li** [comment]
@bitdust 
发现问题了；

我用你的 release 的 mod 就可以，然而在源代码中的 mod 就不可以。

原因在于 `config.ini` 的 html 和 png 的路径不对

同时，`chinese.html` 并没有使用 UTF-8 编码导致 macOS 下乱码

**Comment by bitdust** [comment]
搜噶～我回去修改下
