### ISSUE TITLE
为什么我打开之后，程序一片白色

### ISSUE THREAD

**Issue by turing-king** [bitdust/WamaCry#16]
根本看不清内容啊~
win10系统

**Comment by turing-king** [comment]
@bitdust  是最新的~

**Comment by bitdust** [comment]
在程序目录下面有个mod目录，里面的config.ini文件内容贴一下？

**Comment by wafer-li** [comment]
估计原因和 https://github.com/bitdust/WamaCry/issues/14#issuecomment-301731900 一样；

是因为 `config.ini` 中的 HTML 和 PNG 的目录配置错误导致的。

不过很神奇的发现你的 release 中的 `config.ini` 的目录是对的。

**Comment by bitdust** [comment]
因为没有找到自动化生成mod文件夹的办法，所以估计是我来回拷贝乱了
