### ISSUE TITLE
image

### ISSUE THREAD

**Issue by bitdust** [bitdust/WamaCry#2]
![clipboard03](https://cloud.githubusercontent.com/assets/6072743/26030200/1ca3370a-387e-11e7-9c6d-8d1b029c90cc.png)

**Comment by bitdust** [comment]
![clipboard01](https://cloud.githubusercontent.com/assets/6072743/26055547/f4e27056-39a3-11e7-8c01-5d895445f953.png)

**Comment by bitdust** [comment]
![clipboard01](https://cloud.githubusercontent.com/assets/6072743/26055562/06d88bf6-39a4-11e7-9bf5-807d89c0b39d.png)

**Comment by bitdust** [comment]
![clipboard02](https://cloud.githubusercontent.com/assets/6072743/26056319/676d69f2-39a7-11e7-8fea-94246ef58467.png)

**Comment by bitdust** [comment]
![3](https://cloud.githubusercontent.com/assets/6072743/26116817/0b16075e-3a97-11e7-8819-2d4e475f4627.gif)

**Comment by bitdust** [comment]
![3](https://cloud.githubusercontent.com/assets/6072743/26133474/e2aee0ea-3ad9-11e7-8aeb-b434e277491a.gif)

**Comment by junliangi** [comment]
刚刚我把这个假的WamaCry给放到了舍友的电脑里，舍友看到时一脸惊讶感觉还有一种打死我我冲动......
