### ISSUE TITLE
全屏显示有问题

### ISSUE THREAD

**Issue by poxxz** [bitdust/WamaCry#5]
全屏的话里面的东西没有自适应哈哈哈哈

**Comment by bitdust** [comment]
啊啊我不知道怎么屏蔽全屏按钮！

**Comment by bitdust** [comment]
solved

**Comment by iVanilla** [comment]
@bitdust 即使你能取消最大化按钮, 但我会告诉你, 任务管理器能强制全屏吗?  (逃

PS: 我写的版本会自适应, 毕竟纯手写代码构造界面 (逃

**Comment by bitdust** [comment]
@iVanilla 啊，你就是V2EX上怼我那位？欢迎提PR 😄

**Comment by iVanilla** [comment]
@bitdust 我都自己写了一个, 而且我的目标是高仿, 不是真 恶搞(手动滑稽)

https://github.com/iVanilla/FakeWannaCry
