### ISSUE TITLE
语言选择问题

### ISSUE THREAD

**Issue by Veryjius** [bitdust/WamaCry#9]
语言选择那里中文应该细分为Simplified-Chinese和TraditionalT-Chinese而不只是“中文”

**Comment by bitdust** [comment]
我太懒了。。。

**Comment by bitpeach** [comment]
@Veryjius Good idea! Good advice!

@bitdust You are too lazy! Couldn't you listen to this language option suggestion? I consider that you just change the const display or some words, then you can get that "Simplified-Chinese" display.
